#!/usr/bin/env bash

set -e

REGION="eu-central-1"
SERVICE_ROLE_STACK="SDL-Service-Roles"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "====Deploy SDL Service Role and S3 Bucket via CloudFormation using Admin account===="

echo ""
echo "---- [1/1] Deploying Service Roles and S3 stack: $SERVICE_ROLE_STACK ----"
aws --profile admin cloudformation deploy \
  --template-file "$SCRIPT_DIR/iam-freeconciled.json" \
  --stack-name $SERVICE_ROLE_STACK \
  --region $REGION \
  --capabilities CAPABILITY_NAMED_IAM